import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Link href="Simon">Simon</Link>
			</main>
		</div>
	);
}
